import argparse
import logging
import sys

from .analysis import run_analysis
from .visualize import run_visualization

def setup_logging():
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
        stream=sys.stdout
    )

def main():
    setup_logging()
    parser = argparse.ArgumentParser(description="water_bridges-Nw: A hybrid algorithm for water network detection.")
    subparsers = parser.add_subparsers(dest="command", help="Sub-commands")
    subparsers.required = True

    # --- Calculate Subcommand ---
    calc_parser = subparsers.add_parser("calculate", help="Analyze trajectory to find water networks.")
    calc_parser.add_argument("--topo", required=True, help="Topology file (e.g., .pdb, .tpr).")
    calc_parser.add_argument("--traj", required=False, help="Trajectory file (e.g., .xtc, .dcd). If not provided, evaluates only topology.")
    calc_parser.add_argument("--root", required=True, help="MDAnalysis selection string for the root atoms (e.g., 'resname LIG').")
    calc_parser.add_argument("--water", default="resname SOL or resname WAT or resname HOH", help="MDAnalysis selection string for water.")
    calc_parser.add_argument("--stride", type=int, default=1, help="Frame stride for trajectory processing.")
    calc_parser.add_argument("--max_depth", type=int, default=10, help="Maximum number of consecutive waters in a path.")
    calc_parser.add_argument("--min_depth", type=int, default=1, help="Minimum path length to save in results.")
    calc_parser.add_argument("--cooperativity", type=float, default=0.92, help="Depth-dependent cooperativity factor for hydrogen bonds.")
    calc_parser.add_argument("--coarse_cutoff", type=float, default=4.5, help="Coarse distance cutoff (Angstroms) for initial graph building.")
    calc_parser.add_argument("--output", default="results.jsonl", help="Output JSON Lines file for storing the raw network data.")
    calc_parser.add_argument("--csv", default=None, help="Optional output CSV file for storing human-readable summary data.")

    # --cluster / --cluster_threshold are kept for backward compatibility but are deprecated in favour of the dedicated 'cluster' sub-command below.
    calc_parser.add_argument("--cluster", action="store_true", help="Enable temporal clustering of pathways post-analysis.")
    calc_parser.add_argument("--cluster_threshold", type=float, default=3.5, help="Spatial threshold for for the deprecated inline clustering.")
    
    # cluster sub-command  (NEW – decoupled from 'calculate')
    cluster_parser = subparsers.add_parser("cluster", help="Cluster pathways from a finished calculation without re-running the MD analysis.",)
    cluster_parser.add_argument("--data", required=True, help="Input JSONL file generated by the 'calculate' sub-command.")
    cluster_parser.add_argument("--threshold", type=float, default=3.5,
        help="Centroid-distance threshold (Å) for average-link clustering. "
             "Lower values produce finer clusters. " #Verify
             "Note: centroid distances are ≤ Hausdorff distances, so if you " #Verify
             "previously used a Hausdorff threshold you may want to reduce " #Verify
             "this slightly (e.g. 2.5–3.0 Å).") #Verify
    cluster_parser.add_argument("--output", default="clustered_pathways.json", 
        help="Output JSON file for the cluster summary.")

    
    # --- Visualize Subcommand ---
    vis_parser = subparsers.add_parser("visualize", help="Generate visualization scripts from calculation results.")
    vis_parser.add_argument("--data", required=True, help="Input JSONL file generated by the 'calculate' command.")
    vis_parser.add_argument("--format", choices=["vmd", "pymol", "chimera"], default="vmd", help="Target visualization software.")
    vis_parser.add_argument("--mode", choices=["density", "frame"], default="density", help="Visualization mode: 'density' (all frames) or 'frame' (single frame).")
    vis_parser.add_argument("--frame", type=int, default=None, help="Frame index to visualize (only used if mode='frame').")
    vis_parser.add_argument("--output", default="pathways_viz", help="Output script file name or prefix.")

    args = parser.parse_args()

    if args.command == "calculate":
        run_analysis(
            topo_file=args.topo,
            traj_file=args.traj,
            root_sel=args.root,
            water_sel=args.water,
            stride=args.stride,
            max_depth=args.max_depth,
            min_depth=args.min_depth,
            prob_threshold=args.prob_threshold,
            cooperativity=args.cooperativity,
            coarse_cutoff=args.coarse_cutoff,
            output_file=args.output,
            csv_file=args.csv,
            cluster=args.cluster,
            cluster_threshold=args.cluster_threshold
        )

    elif args.command == "cluster":
        cluster_pathways(
            data_file=args.data,
            threshold=args.threshold,
            output_file=args.output,
        )
        
    elif args.command == "visualize":
        run_visualization(
            data_file=args.data,
            format=args.format,
            mode=args.mode,
            frame_idx=args.frame,
            output_file=args.output
        )

if __name__ == "__main__":
    main()
